monolog:
    channels: ['mbt']
    handlers:
        slack:
            type: slack
            token: 'xxxx-xxxxxxxxxxx-xxxxxxxxx-xxxxxxxxxx-xxxxxx'
            channel: '#name-of-channel'
            channels: [mbt]
            level: error
        swift:
            type: swift_mailer
            from_email: 'mbt@example.com'
            to_email:   'error@example.com'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:      'A Bug Was Found!'
            formatter: mbt.bug_formatter
            content_type: text/html
            channels: [mbt]
            level: error
