apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/services/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
  namespace: mbt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/services/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: admin
    spec:
      containers:
      - env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: admin-docker--env
        image: tienvx/mbt-admin:v1.17.0
        name: admin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
