apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/services/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api-nginx
  name: api-nginx
  namespace: mbt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/services/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api-nginx
    spec:
      containers:
      - image: tienvx/mbt-examples-api-nginx:v1.17.0
        name: api-nginx
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
