apiVersion: v1
data:
  MYSQL_DATABASE: db
  MYSQL_PASSWORD: pass
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-docker--env-db
  name: db-docker--env-db
  namespace: mbt
