apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/services/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
  namespace: mbt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/services/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - -c
        - mkdir -p /data/mbt && minio server --address :9000 /data
        command:
        - sh
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_ACCESS_KEY
              name: minio-docker--env-minio
        - name: MINIO_REGION
          valueFrom:
            configMapKeyRef:
              key: MINIO_REGION
              name: minio-docker--env-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: MINIO_SECRET_KEY
              name: minio-docker--env-minio
        image: minio/minio
        name: minio
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
