name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: 7.4

    - name: Install Dependencies
      run: composer install

    - name: PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run

    - name: Test
      run: php bin/phpunit
      env:
        SYMFONY_DEPRECATIONS_HELPER: disabled
